# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb4611c0934dbc7c9e1fa39cebb027f9c6ccee11ffa3f7b8daf07ad27e67126c55c73f14af87c2fef2ca415ed7f4345df14e9854163ccbf12f03beb1628453c1

test:
  secret_key_base: 08a75451b4835c09ce78cd6c1859769b8dd682de941343cbe99a51a44d1172d7c39f519aa7464252006e21807739f742a25f5a62a62bd54fa0c7eff20ae2c097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
